project_id = "awdwtzawimyiavcsaddu"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:5173", "https://localhost:5173"]
jwt_expiry = 3600

[db]
port = 54322

[functions.process-import]
verify_jwt = true

[functions.import-diagnostics]
verify_jwt = false