// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awdwtzawimyiavcsaddu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3ZHd0emF3aW15aWF2Y3NhZGR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NDI3OTUsImV4cCI6MjA3MTIxODc5NX0.JboQMlWHLFVioBCNGbSC27lh-eOleYOs_atdt0X2z8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});